version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cektagihan_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_HOST=db
      - DB_DATABASE=
      - DB_USER=
      - DB_PASSWORD=
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - BROADCAST_DRIVER=pusher
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
    depends_on:
      - db
      - redis
    networks:
      - cek_tagihan_network

  web:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cek_tagihan_network

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cek_tagihan_network

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cek_tagihan_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue_worker
    restart: unless-stopped
    working_dir: /var/www
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    depends_on:
      - app
      - redis
    networks:
      - cek_tagihan_network

networks:
  cek_tagihan_network:
    driver: bridge


volumes:
  db_data
